/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model.glb --transform --types 
Files: public/model.glb [21.08MB] > C:\0_Ironance_Folder\02_Learning\01_ProgramLearning\5_3js\react-3d-demo\model-transformed.glb [1.92MB] (91%)
Author: Karol Miklas (https://sketchfab.com/karolmiklas)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/free-porsche-911-carrera-4s-d01b254483794de3819786d93e0e1ebf
Title: (FREE) Porsche 911 Carrera 4S
*/

// import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
// import type { GLTF } from 'three-stdlib';

type GLTFResult = any;
// GLTF & {
//   nodes: {
//     window_rear_0: THREE.Mesh
//     windshield_1: THREE.Mesh
//     Plane002_0: THREE.Mesh
//     Cylinder000_0: THREE.Mesh
//     Cylinder000_2: THREE.Mesh
//     Plane_0: THREE.Mesh
//     bumper_front004_1: THREE.Mesh
//     bumper_front007_0: THREE.Mesh
//     bumper_front009_0: THREE.Mesh
//     boot007_0: THREE.Mesh
//     Plane005_0: THREE.Mesh
//     boot011_0: THREE.Mesh
//   }
//   materials: {
//     PaletteMaterial001: THREE.MeshPhysicalMaterial
//     PaletteMaterial002: THREE.MeshStandardMaterial
//     paint: THREE.MeshStandardMaterial
//     PaletteMaterial003: THREE.MeshPhysicalMaterial
//     rubber: THREE.MeshStandardMaterial
//     Material: THREE.MeshStandardMaterial
//     PaletteMaterial004: THREE.MeshPhysicalMaterial
//     PaletteMaterial005: THREE.MeshPhysicalMaterial
//     tex_shiny: THREE.MeshPhysicalMaterial
//     logo: THREE.MeshStandardMaterial
//     license: THREE.MeshStandardMaterial
//     PaletteMaterial006: THREE.MeshStandardMaterial
//   }
//   animations: GLTFAction[]
// }

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model-transformed.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.window_rear_0.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.015, -0.009, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.windshield_1.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.015, -0.005, 0.065]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Plane002_0.geometry}
        material={materials.paint}
        position={[-0.624, -0.082, -1.968]}
        rotation={[-3.01, -0.62, 0.775]}
        scale={0.014}
      />
      <mesh
        geometry={nodes.Cylinder000_0.geometry}
        material={materials.PaletteMaterial003}
        position={[-0.015, 0.008, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Cylinder000_2.geometry}
        material={materials.rubber}
        position={[-0.015, 0.008, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Plane_0.geometry}
        material={materials.Material}
        position={[-0.015, -0.619, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[4.022, 5.66, 4.336]}
      />
      <mesh
        geometry={nodes.bumper_front004_1.geometry}
        material={materials.PaletteMaterial004}
        position={[-0.015, -0.009, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.bumper_front007_0.geometry}
        material={materials.PaletteMaterial005}
        position={[-0.015, -0.009, 0.063]}
        rotation={[-1.577, 0, 0]}
        scale={0.599}
      />
      <mesh
        geometry={nodes.bumper_front009_0.geometry}
        material={materials.tex_shiny}
        position={[-0.015, -0.009, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.boot007_0.geometry}
        material={materials.logo}
        position={[-0.015, -0.009, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Plane005_0.geometry}
        material={materials.license}
        position={[-0.015, -0.178, -2.08]}
        rotation={[-1.457, 0, 0]}
        scale={[0.228, 0.228, 0.206]}
      />
      <mesh
        geometry={nodes.boot011_0.geometry}
        material={materials.PaletteMaterial006}
        position={[-0.015, -0.009, 0.063]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.578}
      />
    </group>
  );
}

useGLTF.preload('/model-transformed.glb');
